In [13]:
import numpy as np
U=np.array([[0,1],[1,0]]).conjugate().transpose()
Y=np.array([[0,1],[1,0]])
np.matmul(U,Y)

array([[1, 0],
       [0, 1]])

In [75]:
import numpy as np
coeff_of_11=input('enter coefficient of matrix at position (1,1): ')
coeff_of_12=input('enter coefficient of matrix at position (1,2): ')
coeff_of_21=input('enter coefficient of matrix at position (2,1): ')
coeff_of_22=input('enter coefficient of matrix at position (2,2): ')
α=np.array([[coeff_of_11],[coeff_of_21]])
β=np.array([[coeff_of_12],[coeff_of_22]])
def gate_validater(α,β):
    P=np.array([[α],[β]])
    Q=P.conjugate().transpose()
    if np.dot(P,Q)==np.dot(Q,P):
        if np.dot(P,Q)==np.array([[1,0],[0,1]]):
            return 'valid gate'
        else:
            return 'invalid gate'
    else:
        return 'invalid gate'
gate_validater(α,β)

enter coefficient of matrix at position (1,1): 1
enter coefficient of matrix at position (1,2): 1
enter coefficient of matrix at position (2,1): 1
enter coefficient of matrix at position (2,2): 1


//anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: DeprecationWarning: attempting to conjugate non-numeric dtype; this will error in the future to match the behavior of np.conjugate
  # Remove the CWD from sys.path while we load stuff.


ValueError: data type must provide an itemsize

In [39]:
import math
a=np.array([[1],[0]])
b=np.array([[1],[0]]).transpose()
c=np.dot(b,a).round()
if c==1:
    print('valid')
else:
    print('invalid')
c

valid


array([[1]])

In [44]:
coeff_of_11=10
print(coeff_of_11)

10


In [70]:
np.matmul(U,Z)



array([[1, 0],
       [0, 1]])

In [71]:
np.matmul(Z,U)

array([[1, 0],
       [0, 1]])

In [72]:
U

array([[0, 1],
       [1, 0]])

In [16]:
import numpy as np
import math


# checking validity
def gate_validator(Q):
    Q1=Q.conjugate().transpose()
    Q2=np.array([[1,0],[0,1]])
    if np.dot(Q,Q1).all()==Q2.all():
        return 'valid'
    else:
        return 'invalid'
        
        
        
#defining pauli X gate
def pauli_X(Q):
    gate_validator(Q)
    X=np.array([[0,1],[1,0]])
    return np.matmul(X,Q)


# defining pauli Y gate
def pauli_Y(Q):
    gate_validator(Q)
    Y=np.array([[0,-1j],[1j,0]])
    return np.matmul(Y,Q)



# defining pauli Z gate
def pauli_Z(Q):
    gate_validator(Q)
    Z=np.array([[1,0],[0,-1]])
    return np.matmul(Z,Q)


# defining Hadamard gate
def pauli_H(Q):
    gate_validator(Q)
    H=np.array([[1/math.sqrt(2),1/math.sqrt(2)],[1/math.sqrt(2),-1/math.sqrt(2)]])
    return np.matmul(H,Q)



# defining CNOT gate
# enter Q as crossproduct of the two qubits i.e np.kron(qubit,qubit2)
def CNOT1(Q):
    gate_validator(Q)
    CNOT=np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
    return np.matmul(CNOT,Q)

def CNOT2(Q1,Q2):
    gate_validator(Q1)
    gate_validator(Q2)
    CNOT=np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
    Q=np.kron(Q1,Q2)
    return np.matmul(CNOT,Q)
    
    
    
# defining CCNOT gate(type1)
# take crossproduct first two qubits as np.kron(qubit1,qubit2) and then take crossproduct of the result with third qubit in the same way as done before
def CCNOT1(Q):
    gate_validator(Q)
    CCNOT=np.array([[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0]])
    return np.matmul(CCNOT,Q)



# defining CCNOT gate(type2)
# enter three qubits in the function
def CCNOT2(Q1,Q2,Q3):
    gate_validator(Q1)
    gate_validator(Q2)
    gate_validator(Q3)
    CCNOT=np.array([[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0],[0,0,0,0,0,1,0,0],[0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0]])
    Q=np.kron(Q1,Q2)
    Q=np.kron(Q,Q3)
    return np.matmul(CCNOT,Q)


# defining swap gate(type1)
def SWAP1(Q1,Q2):
    gate_validator(Q1)
    gate_validator(Q2)
    SWAP1=np.array([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]])
    Q=np.kron(Q1,Q2)
    return np.matmul(SWAP1,Q)


# defining swap gate(type2)
# Q=np.kron(Q1,Q2)
def SWAP2(Q):
    gate_validator(Q)
    SWAP2=np.array([[1,0,0,0],[0,0,1,0],[0,1,0,0],[0,0,0,1]])
    return np.matmul(SWAP2,Q)



# Combining gates

def XZ(Q):
    gate_validator(Q)
    XZ=pauli_X(pauli_Z(Q))
    return XZ

def YZ(Q):
    gate_validator(Q)
    YZ=pauli_Y(pauli_Z(Q))
    return YZ

def XY(Q):
    gate_validator(Q)
    XY=pauli_X(pauli_Y(Q))
    return XY
    
def HX(Q):
    gate_validator(Q)
    HX=pauli_H(pauli_X(Q))
    return HX

def HY(Q):
    gate_validator(Q)
    HY=pauli_H(pauli_Y(Q))
    return HY

def HZ(Q):
    gate_validator(Q)
    HZ=pauli_H(pauli_Z(Q))
    return HZ

pauli_H(np.array([[0.70710678],[-0.70710678]]))

array([[0.],
       [1.]])

In [23]:
def gate_validator(Q):
    Q1=Q.conjugate().transpose()
    Q2=np.array([[1,0],[0,1]])
    if np.matmul(Q,Q1).all()==Q2.all():
        return 'valid'
    else:
        return 'invalid'
gate_validator(np.array([[1],[1]]))

'invalid'

In [133]:
def CNOT(Q):
    CNOT=np.array([[1,0,0,0],[0,1,0,0],[0,0,0,1],[0,0,1,0]])
    return np.matmul(CNOT,Q)
Q=np.kron([1,0],[1,0])
CNOT(Q)

array([1, 0, 0, 0])

In [141]:
Q1=np.array([[1,0]])
Q2=np.array([[0,1]])
Q=np.kron(Q1,Q2)
Q

array([[0, 1, 0, 0]])

In [144]:
def CCNOT(Q):
    CCNOT=np.array([[1,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0],[0,0,1,0,0,0,0,0],[0,0,0,1,0,0,0,0],[0,0,0,0,1,0,0,0],[0,0,0,0,0,0,0,1],[0,0,0,0,0,0,1,0]])
    return np.matmul(CCNOT,Q)
Q=np.kron([0,1],[0,1])
Q=np.kron(Q,[1,0])
CCNOT(Q)

array([0, 0, 0, 0, 0, 0, 1])

In [170]:
def gate_validator(Q1,Q2):
    if np.dot(Q1,Q2)==[[1,0],[0,1]]:
        return 'valid gate'
    else:
        return 'invalid gate'
Q1=np.array([[0,1],[1,0]])
Q2=Q1.conjugate().transpose()
I=np.array([[1,0],[0,1]])
gate_validator(Q1,Q2).all()


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [172]:
def XZ(Q):
    XZ=pauli_X(pauli_Z(Q))
    return XZ
XZ(np.array([[1],[0]]))

array([[0],
       [1]])

In [195]:
q=np.array([[0,1],[1,0]])
q1=q.conjugate().transpose()
q2=np.array([[1,0],[0,1]])
if np.dot(q,q1).all()==q2.all():
    print('valid')
else:
    print('invalid')
np.dot(q,q1)

valid


array([[1, 0],
       [0, 1]])

In [197]:
def gate_validator(Q):
    Q1=Q.conjugate().transpose()
    Q2=np.array([[1,0],[0,1]])
    if np.dot(Q,Q1).all()==Q2.all():
        print('valid')
    else:
        print('invalid')
        
gate_validator(np.array([[1,1],[1,1]]))

invalid


In [6]:
import numpy as np
import math
a=np.array([[1],[0]])
b=np.array([[1],[1]])
b=b.conjugate().transpose()
print(np.dot(a,b))
print(np.matmul(a,b))
print(a)
print(b)

[[1 1]
 [0 0]]
[[1 1]
 [0 0]]
[[1]
 [0]]
[[1 1]]


In [10]:
def pauli_X(Q):
    X=np.array([[0,1],[1,0]])
    return np.matmul(X,Q)
def pauli_Z(Q):
    Z=np.array([[1,0],[0,-1]])
    return np.matmul(Z,Q)
def XZ(Q):
    XZ=pauli_X(pauli_Z(Q))
    return XZ
def YZ(Q):
    YZ=pauli_Y(pauli_Z(Q))
    return YZ
def pauli_Y(Q):
    Y=np.array([[0,-1j],[1j,0]])
    return np.matmul(Y,Q)
YZ(np.array([[0],[1]]))

array([[0.+1.j],
       [0.+0.j]])